### PR TITLE
Add support for Double Precision

### PR DESCRIPTION
**Pull request by michaelsakharov**
## Double Precision
This PR adds double precision support while maintaining the existing SIMD-accelerated float performance. Double precision can be enabled via the `USE_DOUBLE_PRECISION` scripting define.

## Key Features
- Conditional compilation support for both single and double-precision
- Preserved SIMD acceleration for float operations
- Memory layout adjustments for proper alignment in both modes
- All existing tests passing in both precision modes
- Split Contact.cs implementation into two specialized versions:
  - `Contact.Float`: Maintains the original high-performance SIMD implementation
  - `Contact.Double`: Simplified scalar version optimized for just double precision

## Usage
To enable double precision:
1. Add `USE_DOUBLE_PRECISION` to your project's scripting define symbols
2. Rebuild the project
3. All Real "types" will now use double-precision

## Breaking Changes
None. This is a completely opt-in feature the default (float) precision requires no changes to existing projects.

## Notes
The commit history is a bit messy. The first commit was an initial port to Doubles before I decided to make it a pull request.
So it got reverted and remade but as a define so that it's optional.

### CODE REVIEW

**Comment by PaperPrototype** [comment]
YES FINALLY

**Comment by notgiven688** [comment]
@michaelsakharov Looks good to me. In-depth review may take a few days.

**Comment by notgiven688** [comment]
Instead of
```cs
#if USE_DOUBLE_PRECISION
using Real = System.Double;
using MathR = System.Math;
#else
using Real = System.Single;
using MathR = System.MathF;
#endif
```
in every file, can we get away with a single "GlobalUsings.cs" with
```cs
#if USE_DOUBLE_PRECISION
global using Real = System.Double;
global using MathR = System.Math;
#else
global using Real = System.Single;
global using MathR = System.MathF;
#endif
```
?

**Comment by notgiven688** [comment]
Something else to consider: Can we use Vector256 for double precision SIMD in Contact.cs?

Another point:

FieldOffsets could be set like this:

```cs
[FieldOffset(GlobalConstants.SizeReal)]
public Real Bias;
```

with 

```cs
#if USE_DOUBLE_PRECISION

global using Real = System.Double;
global using MathR = System.Math;

public static class GlobalConstants
{
    public const int SizeReal = 8;
}

#else

global using Real = System.Single;
global using MathR = System.MathF;

public static class GlobalConstants
{
    public const int SizeReal = 4;
}

#endif
```

**Comment by michaelsakharov** [comment]
> Something else to consider: Can we use Vector256 for double precision SIMD in Contact.cs?
> 
> Another point:
> 
> FieldOffsets could be set like this:
> 
> ```cs
> [FieldOffset(GlobalConstants.SizeReal)]
> public Real Bias;
> ```
> 
> with
> 
> ```cs
> #if USE_DOUBLE_PRECISION
> 
> global using Real = System.Double;
> global using MathR = System.Math;
> 
> public static class GlobalConstants
> {
>     public const int SizeReal = 8;
> }
> 
> #else
> 
> global using Real = System.Single;
> global using MathR = System.MathF;
> 
> public static class GlobalConstants
> {
>     public const int SizeReal = 4;
> }
> 
> #endif
> ```

Im not familiar with SIMD stuff so I unfortunately don't think I can help much there.
With the FieldOffsets doesn't each attribute need a separate value? Would you want me to make a bunch of SizeReal constants? for each used offset?

**Comment by notgiven688** [comment]
Thank you for your contribution. I switched the merge target to a branch here called "double_precision". I will finalize the last bits. Is this okay for you?

**Comment by michaelsakharov** [comment]
Yup! Thanks!

**Pull request merged**
